on: 
  pull_request:
    types: [opened, closed]
name: Deploy
jobs:
  Deploy:
    name: Terraform Deploy
    runs-on: self-hosted
    steps:
    - name: Init
      run: terraform init

    - name: Format
      run: terraform fmt -check

    - name: Plan
      run: terraform plan -input=false

    - name: Apply
      run: terraform apply -auto-approve -input=false
      if: github.event.pull_request.merged == true
